import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'en' | 'fr' | 'ar';

export const translations = {
    en: {
        dashboard: 'Dashboard',
        sales: 'Sales',
        expenses: 'Expenses',
        products: 'Products',
        analytics: 'Analytics',
        settings: 'Settings',
        more: 'More',
        subscriptions: 'Subscriptions',
        mySubscriptions: 'My Subscriptions',
        customerSubscriptions: 'Customer Subscriptions',
        totalRevenue: 'Total Revenue',
        netProfit: 'Net Profit',
        totalSales: 'Total Sales',
        totalExpenses: 'Total Expenses',
        addProduct: 'Add Product',
        recordIncome: 'Record Income',
        addExpense: 'Add Expense',
        appearance: 'Appearance',
        language: 'Language',
        darkMode: 'Dark Mode',
        backupRestore: 'Backup & Restore',
        downloadBackup: 'Download Backup',
        restoreBackup: 'Restore Backup',
        warning: 'Warning',
        restoreWarning: 'Restoring will overwrite all current data.',
        dailySales: 'Daily Sales',
        monthlySales: 'Monthly Sales',
        export: 'Export',
        itemsSold: 'Items Sold',
        today: 'Today',
        thisMonth: 'This Month',
        topProducts: 'Top Products',
        recentActivity: 'Recent Activity',
        revenue: 'Revenue',
        quantity: 'Quantity',
        date: 'Date',
        actions: 'Actions',
        delete: 'Delete',
        edit: 'Edit',
        total: 'Total',
        category: 'Category',
        description: 'Description',
        amount: 'Amount',
        price: 'Price',
        cost: 'Cost',
        stock: 'Stock',
        inventory: 'Inventory',
        profit: 'Profit',
        margin: 'Margin',
        unknown: 'Unknown',
        incomeDashboard: 'Income Dashboard',
        dailyExport: 'Daily Export',
        exportDailySalesToExcel: 'Export daily sales to Excel',
        exporting: 'Exporting...',
        exportDaily: 'Export Daily',
        monthlyExport: 'Monthly Export',
        exportMonthlySalesToExcel: 'Export monthly sales to Excel',
        exportMonthly: 'Export Monthly',
        todaysStats: "Today's Stats",
        todaysRevenue: "Today's Revenue",
        todaysSales: "Today's Sales",
        itemsSoldToday: 'Items Sold Today',
        productsOverview: 'Products Overview',
        noProductsAddedYet: 'No products added yet.',
        deleteProduct: 'Delete product',
        income: 'Income',
        sold: 'Sold',
        lastSale: 'Last sale',
        recentIncomeEntries: 'Recent Income Entries',
        noIncomeEntriesYet: 'No income entries yet.',
        deleteEntry: 'Delete entry',
        totalIncome: 'Total Income',
        incomeDashboardTitle: 'Income Dashboard',
        todaysOverview: "Today's Overview",
        noProductsAvailable: 'No products available.',
        clickToAddProduct: 'Click "Add Product" to get started!',
        addNewProduct: 'Add New Product',
        close: 'Close',
        expenseHistory: 'Expense History',
        expenseOverview: 'Expenses Overview',
        analyticsOverview: 'Analytics Overview',
        revenueVsExpenses: 'Revenue vs Expenses',
        netProfitMargin: 'Net Profit Margin',
        revenueByCategory: 'Revenue by Category',
        expensesByCategory: 'Expenses by Category',
        weekly: 'Weekly',
        monthly: 'Monthly',
        yearly: 'Yearly',
        allTime: 'All Time',
        noExpensesYet: 'No expenses recorded yet.',
        confirmDeleteExpense: 'Are you sure you want to delete this expense?',
        notTracked: 'Not Tracked',
        outOfStock: 'Out of Stock',
        lowStock: 'Low Stock',
        inStock: 'En stock', // Mixed up something here? No, 'En stock' is FR. Wait.
        confirmDeleteProduct: 'Are you sure you want to delete this product?',
        editProduct: 'Edit Product',
        all: 'All',
        avgOrderValue: 'Avg. Order Value',
        profitMargin: 'Profit Margin',
        exportAnalytics: 'Export Analytics',
        failedToExport: 'Failed to export analytics. Please try again.',
        analyticsSubtitle: 'Comprehensive insights into your sales performance',
        productName: 'Product Name',
        enterProductName: 'Enter product name',
        selectCategory: 'Select Category',
        optionalDescription: 'Optional description',
        trackInventoryLabel: 'Track Inventory',
        initialStockQuantity: 'Initial stock quantity',
        clickToUploadImage: 'Click to upload image',
        productImage: 'Product Image',
        updateProduct: 'Update Product',
        editExpense: 'Edit Expense',
        recordExpense: 'Record Expense',
        updateExpense: 'Update Expense',
        saveExpense: 'Save Expense',
        fillRequiredFields: 'Please fill in all required fields',
        fillProductNamePrice: 'Please fill in product name and price',
        validPrice: 'Please enter a valid price',
        validAmount: 'Please enter a valid amount',
        validInventory: 'Please enter a valid inventory quantity (0 or greater)',
        selectOrEnterCategory: 'Please select or enter a category',
        failedToAddProduct: 'Failed to add product. Please try again.',
        failedToSaveExpense: 'Failed to save expense. Please try again.',
        failedToRecordIncome: 'Failed to record income. Please try again.',
        failedToExportDaily: 'Failed to export daily sales. Please try again.',
        failedToExportMonthly: 'Failed to export monthly sales. Please try again.',
        expensesSubtitle: 'Track your business costs and overhead',
        settingsSubtitle: 'Manage your application preferences',
        defaultCurrency: 'Default Currency',
        currencyDescription: 'This currency will be used throughout the application.',
        about: 'About',
        aboutDescription: 'A modern web application for tracking income from products.',
        reloadSuccess: 'Data restored successfully! The application will now reload.',
        failedToExportData: 'Failed to export data. Please try again.',
        failedToRestoreData: 'Failed to restore data.',
        confirmDeleteProductWithEntries: 'Are you sure you want to delete this product? This will also delete all related income entries.',
        confirmDeleteEntry: 'Are you sure you want to delete this income entry?',
        on: 'On',
        off: 'Off',
        currency: 'Currency',
        backupRestoreDescription: 'Securely backup your entire dataset to a JSON file or restore from a previous backup.',
        searchPlaceholder: 'Search products, sales...',
        notifications: 'Notifications',
        user: 'User',
        selectImageFile: 'Please select an image file',
        imageSizeLimit: 'Image size should be less than 5MB',
        addCustomCategory: 'Add Custom Category',
        enterCustomCategory: 'Enter Custom Category',
        cancel: 'Cancel',
        insufficientStock: 'Insufficient stock! Only {stock} items available.',
        setQuantityGreaterThanZero: 'Please set a quantity greater than 0',
        selectDate: 'Please select a date',
        noProductsAvailableAddFirst: 'No products available. Please add a product first.',
        notesOptional: 'Notes (Optional)',
        optionalNotesPlaceholder: 'Optional notes for all entries',
        confirm: 'Confirm',
        productPerformance: 'Product Performance',
        noSalesDataAvailable: 'No sales data available.',
        soldCount: '{count} sold',
        percentOfTotal: '{percent}% of total',
        breakdownByPeriod: '{period} Breakdown',
        noDataForPeriod: 'No data available for this period.',
        mrr: 'MRR',
        mrc: 'MRC',
        monthlyRecurringRevenue: 'Monthly Recurring Revenue',
        monthlyRecurringCost: 'Monthly Recurring Cost',
        customerName: 'Customer Name',
        serviceName: 'Service Name',
        billingCycle: 'Billing Cycle',
        startDate: 'Start Date',
        nextBillingDate: 'Next Billing Date',
        status: 'Status',
        active: 'Active',
        expired: 'Expired',
        cancelled: 'Cancelled',
        pending: 'Pending',
        paused: 'Paused',
        addSubscription: 'Add Subscription',
        addCustomerSubscription: 'Add Customer',
        mrrDescription: 'Predictable monthly revenue from customer subscriptions.',
        mrcDescription: 'Fixed monthly costs for tools and services.',
        noSubscriptionsFound: 'No subscriptions found.',
        confirmDeleteSubscription: 'Are you sure you want to delete this subscription?',
        salesCount: '{count} sales',
        itemsCount: '{count} items',
        weekOf: 'Week of {date}',
        noProductsFound: 'No products found matching your search.',
        projectedNetProfit: 'Projected Net Profit',
        projectedNetProfitDescription: 'Estimated profit including subscriptions.',
        filterByCustomer: 'Filter by customer',
        filterByStatus: 'Filter by status',
        search: 'Search',
        allStatuses: 'All Statuses',
        welcomeBack: 'Welcome Back',
        loginSubtitle: 'Sign in to access your dashboard',
        registerTitle: 'Create Account',
        registerSubtitle: 'Join FinancePro to track your business growth',
        fillAllFields: 'Please fill in all fields',
        invalidCredentials: 'Invalid email or password',
        alreadyHaveAccount: 'Already have an account?',
        dontHaveAccount: "Don't have an account?",
        signIn: 'Sign In',
        createAccount: 'Create Account',
        signingIn: 'Signing in...',
        creatingAccount: 'Creating Account...',
        clearAll: 'Clear All',
        settingsSaved: 'Settings saved successfully!',
        failedToSaveSettings: 'Failed to save settings.',
        saveChanges: 'Save Changes',
        firstName: 'First Name',
        lastName: 'Last Name',
        emailAddress: 'Email Address',
        password: 'Password',
        confirmPassword: 'Confirm Password',
        fullName: 'Full Name',
        passwordsDoNotMatch: 'Passwords do not match',
        passwordTooShort: 'Password must be at least 6 characters',
        registrationFailed: 'Registration failed. Email might be already taken.',
        logout: 'Logout',
        profile: 'Profile',
    },
    fr: {
        dashboard: 'Tableau de bord',
        sales: 'Ventes',
        expenses: 'Dépenses',
        products: 'Produits',
        analytics: 'Analytique',
        settings: 'Paramètres',
        more: 'Plus',
        subscriptions: 'Abonnements',
        mySubscriptions: 'Mes Abonnements',
        customerSubscriptions: 'Abonnements Clients',
        totalRevenue: 'Revenu Total',
        netProfit: 'Bénéfice Net',
        totalSales: 'Ventes Totales',
        totalExpenses: 'Dépenses Totales',
        addProduct: 'Ajouter Produit',
        recordIncome: 'Enregistrer Revenu',
        addExpense: 'Ajouter Dépense',
        appearance: 'Apparence',
        language: 'Langue',
        darkMode: 'Mode Sombre',
        backupRestore: 'Sauvegarde et Restauration',
        downloadBackup: 'Télécharger Sauvegarde',
        restoreBackup: 'Restaurer Sauvegarde',
        warning: 'Attention',
        restoreWarning: 'La restauration écrasera toutes les données actuelles.',
        dailySales: 'Ventes Quotidiennes',
        monthlySales: 'Ventes Mensuelles',
        export: 'Exporter',
        itemsSold: 'Articles Vendus',
        today: "Aujourd'hui",
        thisMonth: 'Ce Mois-ci',
        topProducts: 'Top Produits',
        recentActivity: 'Activité Récente',
        revenue: 'Revenu',
        quantity: 'Quantité',
        date: 'Date',
        actions: 'Actions',
        delete: 'Supprimer',
        edit: 'Modifier',
        total: 'Total',
        category: 'Catégorie',
        description: 'Description',
        amount: 'Montant',
        price: 'Prix',
        cost: 'Coût',
        stock: 'Stock',
        inventory: 'Inventaire',
        profit: 'Bénéfice',
        margin: 'Marge',
        unknown: 'Inconnu',
        incomeDashboard: 'Tableau des Revenus',
        dailyExport: 'Export Quotidien',
        exportDailySalesToExcel: 'Exporter les ventes quotidiennes vers Excel',
        exporting: 'Exportation...',
        exportDaily: 'Exporter Jour',
        monthlyExport: 'Export Mensuel',
        exportMonthlySalesToExcel: 'Exporter les ventes mensuelles vers Excel',
        exportMonthly: 'Exporter Mois',
        todaysStats: "Stats d'Aujourd'hui",
        todaysRevenue: "Revenu d'Aujourd'hui",
        todaysSales: "Ventes d'Aujourd'hui",
        itemsSoldToday: "Articles Vendus Aujourd'hui",
        productsOverview: 'Aperçu des Produits',
        noProductsAddedYet: 'Aucun produit ajouté.',
        deleteProduct: 'Supprimer produit',
        income: 'Revenu',
        sold: 'Vendu',
        lastSale: 'Dernière vente',
        recentIncomeEntries: 'Entrées de Revenus Récentes',
        noIncomeEntriesYet: 'Aucune entrée de revenu.',
        deleteEntry: 'Supprimer entrée',
        totalIncome: 'Revenu Total global',
        incomeDashboardTitle: 'Tableau de bord des revenus',
        todaysOverview: "Aperçu d'aujourd'hui",
        noProductsAvailable: 'Aucun produit disponible.',
        clickToAddProduct: 'Cliquez sur "Ajouter Produit" pour commencer!',
        addNewProduct: 'Ajouter Nouveau Produit',
        close: 'Fermer',
        expenseHistory: 'Historique des Dépenses',
        expenseOverview: 'Aperçu des Dépenses',
        analyticsOverview: 'Aperçu Analytique',
        revenueVsExpenses: 'Revenu vs Dépenses',
        netProfitMargin: 'Marge de Bénéfice Net',
        revenueByCategory: 'Revenu par Catégorie',
        expensesByCategory: 'Dépenses par Catégorie',
        weekly: 'Hebdomadaire',
        monthly: 'Mensuel',
        yearly: 'Annuel',
        allTime: 'Tout le temps',
        noExpensesYet: 'Aucune dépense enregistrée.',
        confirmDeleteExpense: 'Êtes-vous sûr de vouloir supprimer cette dépense ?',
        notTracked: 'Non suivi',
        outOfStock: 'Rupture de stock',
        lowStock: 'Stock faible',
        inStock: 'En stock',
        confirmDeleteProduct: 'Êtes-vous sûr de vouloir supprimer ce produit ?',
        editProduct: 'Modifier le produit',
        all: 'Tous',
        avgOrderValue: 'Valeur de commande moyenne',
        profitMargin: 'Marge bénéficiaire',
        exportAnalytics: 'Exporter les analyses',
        failedToExport: "Échec de l'exportation des analyses. Veuillez réessayer.",
        analyticsSubtitle: 'Aperçu complet de vos performances de vente',
        productName: 'Nom du produit',
        enterProductName: 'Entrez le nom du produit',
        selectCategory: 'Choisir une catégorie',
        optionalDescription: 'Description facultative',
        trackInventoryLabel: 'Suivi des stocks',
        initialStockQuantity: 'Quantité initiale en stock',
        clickToUploadImage: 'Cliquez pour télécharger une image',
        productImage: 'Image du produit',
        updateProduct: 'Modifier le produit',
        editExpense: 'Modifier la dépense',
        recordExpense: 'Enregistrer une dépense',
        updateExpense: 'Modifier la dépense',
        saveExpense: 'Enregistrer la dépense',
        fillRequiredFields: 'Veuillez remplir tous les champs obligatoires',
        fillProductNamePrice: 'Veuillez remplir le nom et le prix du produit',
        validPrice: 'Veuillez entrer un prix valide',
        validAmount: 'Veuillez entrer un montant valide',
        validInventory: 'Veuillez entrer une quantité de stock valide (0 ou plus)',
        selectOrEnterCategory: 'Veuillez sélectionner ou entrer une catégorie',
        failedToAddProduct: "Échec de l'ajout du produit. Veuillez réessayer.",
        failedToSaveExpense: "Échec de l'enregistrement de la dépense. Veuillez réessayer.",
        failedToRecordIncome: "Échec de l'enregistrement du revenu. Veuillez réessayer.",
        failedToExportDaily: "Échec de l'exportation des ventes quotidiennes. Veuillez réessayer.",
        failedToExportMonthly: "Échec de l'exportation des ventes mensuelles. Veuillez réessayer.",
        expensesSubtitle: 'Suivez vos coûts commerciaux et vos frais généraux',
        settingsSubtitle: 'Gérez vos préférences d\'application',
        defaultCurrency: 'Devise par défaut',
        currencyDescription: 'Cette devise sera utilisée dans toute l\'application.',
        about: 'À propos',
        aboutDescription: 'Une application Web moderne pour suivre les revenus des produits.',
        reloadSuccess: 'Données restaurées avec succès ! L\'application va maintenant redémarrer.',
        failedToExportData: 'Échec de l\'exportation des données. Veuillez réessayer.',
        failedToRestoreData: 'Échec de la restauration des données.',
        confirmDeleteProductWithEntries: 'Êtes-vous sûr de vouloir supprimer ce produit ? Cela supprimera également toutes les entrées de revenus associées.',
        confirmDeleteEntry: 'Êtes-vous sûr de vouloir supprimer cette entrée de revenu ?',
        on: 'Activé',
        off: 'Désactivé',
        currency: 'Devise',
        backupRestoreDescription: 'Sauvegardez en toute sécurité l\'ensemble de vos données dans un fichier JSON ou restaurez-les à partir d\'une sauvegarde précédente.',
        searchPlaceholder: 'Rechercher des produits, des ventes...',
        notifications: 'Notifications',
        user: 'Utilisateur',
        selectImageFile: 'Veuillez sélectionner un fichier image',
        imageSizeLimit: "La taille de l'image doit être inférieure à 5 Mo",
        addCustomCategory: 'Ajouter une catégorie personnalisée',
        enterCustomCategory: 'Entrer une catégorie personnalisée',
        cancel: 'Annuler',
        insufficientStock: 'Stock insuffisant ! Seulement {stock} articles disponibles.',
        setQuantityGreaterThanZero: 'Veuillez définir une quantité supérieure à 0',
        selectDate: 'Veuillez sélectionner une date',
        noProductsAvailableAddFirst: 'Aucun produit disponible. Veuillez d\'abord ajouter un produit.',
        notesOptional: 'Notes (facultatif)',
        optionalNotesPlaceholder: 'Notes facultatives pour toutes les entrées',
        confirm: 'Confirmer',
        productPerformance: 'Performance du produit',
        noSalesDataAvailable: 'Aucune donnée de vente disponible.',
        soldCount: '{count} vendus',
        percentOfTotal: '{percent}% du total',
        breakdownByPeriod: 'Répartition {period}',
        noDataForPeriod: 'Aucune donnée disponible pour cette période.',
        mrr: 'RMM',
        mrc: 'CMM',
        monthlyRecurringRevenue: 'Revenu Mensuel Récurrent',
        monthlyRecurringCost: 'Coût Mensuel Récurrent',
        customerName: 'Nom du Client',
        serviceName: 'Nom du Service',
        billingCycle: 'Cycle de Facturation',
        startDate: 'Date de Début',
        nextBillingDate: 'Prochaine Date de Facturation',
        status: 'Statut',
        active: 'Actif',
        expired: 'Expiré',
        cancelled: 'Annulé',
        pending: 'En attente',
        paused: 'En pause',
        addSubscription: 'Ajouter un Abonnement',
        addCustomerSubscription: 'Ajouter un Client',
        mrrDescription: 'Revenu mensuel prévisible provenant des abonnements clients.',
        mrcDescription: 'Coûts mensuels fixes pour les outils et services.',
        noSubscriptionsFound: 'Aucun abonnement trouvé.',
        confirmDeleteSubscription: 'Êtes-vous sûr de vouloir supprimer cet abonnement ?',
        salesCount: '{count} ventes',
        itemsCount: '{count} articles',
        weekOf: 'Semaine du {date}',
        noProductsFound: 'Aucun produit trouvé correspondant à votre recherche.',
        projectedNetProfit: 'Bénéfice Net Projeté',
        projectedNetProfitDescription: 'Bénéfice estimé incluant les abonnements.',
        filterByCustomer: 'Filtrer par client',
        filterByStatus: 'Filtrer par statut',
        search: 'Rechercher',
        allStatuses: 'Tous les statuts',
        welcomeBack: 'Bon retour',
        loginSubtitle: 'Connectez-vous pour accéder à votre tableau de bord',
        registerTitle: 'Créer un compte',
        registerSubtitle: 'Rejoignez FinancePro pour suivre la croissance de votre entreprise',
        fillAllFields: 'Veuillez remplir tous les champs',
        invalidCredentials: 'Email ou mot de passe invalide',
        alreadyHaveAccount: 'Vous avez déjà un compte ?',
        dontHaveAccount: "Vous n'avez pas de compte ?",
        signIn: 'Se connecter',
        createAccount: 'Créer un compte',
        signingIn: 'Connexion...',
        creatingAccount: 'Création du compte...',
        clearAll: 'Tout effacer',
        settingsSaved: 'Paramètres enregistrés avec succès !',
        failedToSaveSettings: "Échec de l'enregistrement des paramètres.",
        saveChanges: 'Sauvegarder les modifications',
        firstName: 'Prénom',
        lastName: 'Nom',
        emailAddress: 'Adresse e-mail',
        password: 'Mot de passe',
        confirmPassword: 'Confirmer le mot de passe',
        fullName: 'Nom complet',
        passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
        passwordTooShort: 'Le mot de passe doit comporter au moins 6 caractères',
        registrationFailed: "Échec de l'enregistrement. L'e-mail est peut-être déjà utilisé.",
        logout: 'Déconnexion',
        profile: 'Profil',
    },
    ar: {
        dashboard: 'لوحة القيادة',
        sales: 'المبيعات',
        expenses: 'المصروفات',
        products: 'المنتجات',
        analytics: 'التحليلات',
        settings: 'الإعدادات',
        more: 'المزيد',
        subscriptions: 'الاشتراكات',
        mySubscriptions: 'اشتراكاتي',
        customerSubscriptions: 'اشتراكات العملاء',
        totalRevenue: 'إجمالي الإيرادات',
        netProfit: 'صافي الربح',
        totalSales: 'إجمالي المبيعات',
        totalExpenses: 'إجمالي المصروفات',
        addProduct: 'إضافة منتج',
        recordIncome: 'تسجيل دخل',
        addExpense: 'إضافة مصروف',
        appearance: 'المظهر',
        language: 'اللغة',
        darkMode: 'الوضع الداكن',
        backupRestore: 'النسخ الاحتياطي والاستعادة',
        downloadBackup: 'تحميل النسخة الاحتياطية',
        restoreBackup: 'استعادة النسخة الاحتياطية',
        warning: 'تحذير',
        restoreWarning: 'تؤدي الاستعادة إلى استبدال جميع البيانات الحالية.',
        dailySales: 'المبيعات اليومية',
        monthlySales: 'المبيعات الشهرية',
        export: 'تصدير',
        itemsSold: 'القطع المباعة',
        today: 'اليوم',
        thisMonth: 'هذا الشهر',
        topProducts: 'أفضل المنتجات',
        recentActivity: 'النشاط الأخير',
        revenue: 'الإيرادات',
        quantity: 'الكمية',
        date: 'التاريخ',
        actions: 'الإجراءات',
        delete: 'حذف',
        edit: 'تعديل',
        total: 'الإجمالي',
        category: 'الفئة',
        description: 'الوصف',
        amount: 'المبلغ',
        price: 'السعر',
        cost: 'التكلفة',
        stock: 'المخزون',
        inventory: 'المخزون',
        profit: 'الربح',
        margin: 'الهامش',
        unknown: 'غير معروف',
        incomeDashboard: 'لوحة الإيرادات',
        dailyExport: 'تصدير يومي',
        exportDailySalesToExcel: 'تصدير المبيعات اليومية إلى Excel',
        exporting: 'جاري التصدير...',
        exportDaily: 'تصدير اليوم',
        monthlyExport: 'تصدير شهري',
        exportMonthlySalesToExcel: 'تصدير المبيعات الشهرية إلى Excel',
        exportMonthly: 'تصدير الشهر',
        todaysStats: 'إحصائيات اليوم',
        todaysRevenue: 'إيرادات اليوم',
        todaysSales: 'مبيعات اليوم',
        itemsSoldToday: 'القطع المباعة اليوم',
        productsOverview: 'نظرة عامة على المنتجات',
        noProductsAddedYet: 'لم يتم إضافة منتجات بعد.',
        deleteProduct: 'حذف المنتج',
        income: 'إيراد',
        sold: 'مباع',
        lastSale: 'آخر بيع',
        recentIncomeEntries: 'إدخالات الدخل الأخيرة',
        noIncomeEntriesYet: 'لا توجد إدخالات دخل بعد.',
        deleteEntry: 'حذف الإدخال',
        totalIncome: 'إجمالي الدخل',
        incomeDashboardTitle: 'لوحة بيانات الدخل',
        todaysOverview: 'نظرة عامة اليوم',
        noProductsAvailable: 'لا توجد منتجات متاحة.',
        clickToAddProduct: 'انقر فوق "إضافة منتج" للبدء!',
        addNewProduct: 'إضافة منتج جديد',
        close: 'إغلاق',
        expenseHistory: 'سجل المصروفات',
        expenseOverview: 'نظرة عامة على المصروفات',
        analyticsOverview: 'نظرة عامة على التحليلات',
        revenueVsExpenses: 'الإيرادات مقابل المصروفات',
        netProfitMargin: 'هامش صافي الربح',
        revenueByCategory: 'الإيرادات حسب الفئة',
        expensesByCategory: 'المصروفات حسب الفئة',
        weekly: 'أسبوعي',
        monthly: 'شهري',
        yearly: 'سنوي',
        allTime: 'كل الوقت',
        noExpensesYet: 'لم يتم تسجيل أي مصروفات بعد.',
        confirmDeleteExpense: 'هل أنت متأكد أنك تريد حذف هذه المصروفات؟',
        notTracked: 'غير متتبع',
        outOfStock: 'نفد من المخزن',
        lowStock: 'مخزون منخفض',
        inStock: 'في المخزن',
        confirmDeleteProduct: 'هل أنت متأكد أنك تريد حذف هذا المنتج؟',
        editProduct: 'تعديل المنتج',
        all: 'الكل',
        avgOrderValue: 'متوسط قيمة الطلب',
        profitMargin: 'هامش الربح',
        exportAnalytics: 'تصدير التحليلات',
        failedToExport: 'فشل تصدير التحليلات. يرجى المحاولة مرة أخرى.',
        analyticsSubtitle: 'رؤية شاملة لأداء مبيعاتك',
        productName: 'اسم المنتج',
        enterProductName: 'أدخل اسم المنتج',
        selectCategory: 'اختر الفئة',
        optionalDescription: 'وصف اختياري',
        trackInventoryLabel: 'تتبع المخزون',
        initialStockQuantity: 'كمية المخزون الأولية',
        clickToUploadImage: 'انقر لتحميل صورة',
        productImage: 'صورة المنتج',
        updateProduct: 'تحديث المنتج',
        editExpense: 'تعديل المصروف',
        recordExpense: 'تسجيل مصروف',
        updateExpense: 'تحديث المصروف',
        saveExpense: 'حفظ المصروف',
        fillRequiredFields: 'يرجى ملء جميع الحقول المطلوبة',
        fillProductNamePrice: 'يرجى ملء اسم المنتج وسعره',
        validPrice: 'يرجى إدخال سعر صالح',
        validAmount: 'يرجى إدخال مبلغ صالح',
        validInventory: 'يرجى إدخال كمية مخزون صالحة (0 أو أكثر)',
        selectOrEnterCategory: 'يرجى اختيار أو إدخال فئة',
        failedToAddProduct: 'فشل إضافة المنتج. يرجى المحاولة مرة أخرى.',
        failedToSaveExpense: 'فشل حفظ المصروف. يرجى المحاولة مرة أخرى.',
        failedToRecordIncome: 'فشل تسجيل الدخل. يرجى المحاولة مرة أخرى.',
        failedToExportDaily: 'فشل تصدير المبيعات اليومية. يرجى المحاولة مرة أخرى.',
        failedToExportMonthly: 'فشل تصدير المبيعات الشهرية. يرجى المحاولة مرة أخرى.',
        expensesSubtitle: 'تتبع تكاليف عملك والمصاريف العامة',
        settingsSubtitle: 'إدارة تفضيلات التطبيق الخاص بك',
        defaultCurrency: 'العملة الافتراضية',
        currencyDescription: 'سيتم استخدام هذه العملة في جميع أنحاء التطبيق.',
        about: 'حول',
        aboutDescription: 'تطبيق ويب حديث لتتبع الدخل من المنتجات.',
        reloadSuccess: 'تم استعادة البيانات بنجاح! سيتم إعادة تحميل التطبيق الآن.',
        failedToExportData: 'فشل تصدير البيانات. يرجى المحاولة مرة أخرى.',
        failedToRestoreData: 'فشل استعادة البيانات.',
        confirmDeleteProductWithEntries: 'هل أنت متأكد أنك تريد حذف هذا المنتج؟ سيؤدي هذا أيضًا إلى حذف جميع إدخالات الدخل المرتبطة.',
        confirmDeleteEntry: 'هل أنت متأكد أنك تريد حذف إدخال الدخل هذا؟',
        on: 'تشغيل',
        off: 'إيقاف',
        currency: 'العملة',
        backupRestoreDescription: 'قم بنسخ مجموعة البيانات بالكامل احتياطيًا بشكل آمن إلى ملف JSON أو استعادتها من نسخة احتياطية سابقة.',
        searchPlaceholder: 'البحث عن المنتجات والمبيعات...',
        notifications: 'تنبيهات',
        user: 'مستخدم',
        selectImageFile: 'يرجى اختيار ملف صورة',
        imageSizeLimit: 'يجب أن يكون حجم الصورة أقل من 5 ميجابايت',
        addCustomCategory: 'إضافة فئة مخصصة',
        enterCustomCategory: 'إدخال فئة مخصصة',
        cancel: 'إلغاء',
        insufficientStock: 'المخزون غير كافٍ! متوفر {stock} قطع فقط.',
        setQuantityGreaterThanZero: 'يرجى تحديد كمية أكبر من 0',
        selectDate: 'يرجى اختيار التاريخ',
        noProductsAvailableAddFirst: 'لا توجد منتجات متاحة. يرجى إضافة منتج أولاً.',
        notesOptional: 'ملاحظات (اختياري)',
        optionalNotesPlaceholder: 'ملاحظات اختيارية لجميع الإدخالات',
        confirm: 'تأكيد',
        productPerformance: 'أداء المنتج',
        noSalesDataAvailable: 'لا توجد بيانات مبيعات متاحة.',
        soldCount: 'تم بيع {count}',
        percentOfTotal: '{percent}% من الإجمالي',
        breakdownByPeriod: 'توزيع {period}',
        noDataForPeriod: 'لا توجد بيانات متاحة لهذه الفترة.',
        mrr: 'MRR',
        mrc: 'MRC',
        monthlyRecurringRevenue: 'الإيرادات الشهرية المتكررة',
        monthlyRecurringCost: 'التكاليف الشهرية المتكررة',
        customerName: 'اسم العميل',
        serviceName: 'اسم الخدمة',
        billingCycle: 'دورة الفوترة',
        startDate: 'تاريخ البدء',
        nextBillingDate: 'تاريخ الفاتورة القادمة',
        status: 'الحالة',
        active: 'نشط',
        expired: 'منتهي',
        cancelled: 'ملغى',
        pending: 'قيد الانتظار',
        paused: 'متوقف مؤقتاً',
        addSubscription: 'إضافة اشتراك',
        addCustomerSubscription: 'إضافة عميل',
        mrrDescription: 'الإيرادات الشهرية المتوقعة من اشتراكات العملاء.',
        mrcDescription: 'التكاليف الشهرية الثابتة للأدوات والخدمات.',
        noSubscriptionsFound: 'لم يتم العثور على اشتراكات.',
        confirmDeleteSubscription: 'هل أنت متأكد أنك تريد حذف هذا الاشتراك؟',
        salesCount: '{count} مبيعات',
        itemsCount: '{count} قطع',
        weekOf: 'أسبوع {date}',
        noProductsFound: 'لم يتم العثور على منتجات تطابق بحثك.',
        projectedNetProfit: 'صافي الربح المتوقع',
        projectedNetProfitDescription: 'الربح التقديري شاملاً الاشتراكات.',
        filterByCustomer: 'تصفية حسب العميل',
        filterByStatus: 'تصفية حسب الحالة',
        search: 'بحث',
        allStatuses: 'جميع الحالات',
        welcomeBack: 'مرحباً بعودتك',
        loginSubtitle: 'سجل الدخول للوصول إلى لوحة التحكم الخاصة بك',
        registerTitle: 'إنشاء حساب',
        registerSubtitle: 'انضم إلى FinancePro لتتبع نمو عملك',
        fillAllFields: 'يرجى ملء جميع الحقول',
        invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صالحة',
        alreadyHaveAccount: 'لديك حساب بالفعل؟',
        dontHaveAccount: 'ليس لديك حساب؟',
        signIn: 'تسجيل الدخول',
        createAccount: 'إنشاء حساب',
        signingIn: 'جاري تسجيل الدخول...',
        creatingAccount: 'جاري إنشاء الحساب...',
        clearAll: 'مسح الكل',
        settingsSaved: 'تم حفظ الإعدادات بنجاح!',
        failedToSaveSettings: 'فشل في حفظ الإعدادات.',
        saveChanges: 'حفظ التغييرات',
        firstName: 'الاسم الأول',
        lastName: 'اسم العائلة',
        emailAddress: 'عنوان البريد الإلكتروني',
        password: 'كلمة المرور',
        confirmPassword: 'تأكيد كلمة المرور',
        fullName: 'الاسم الكامل',
        passwordsDoNotMatch: 'كلمات المرور غير متطابقة',
        passwordTooShort: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
        registrationFailed: 'فشل التسجيل. قد يكون البريد الإلكتروني مستخدمًا بالفعل.',
        logout: 'تسجيل الخروج',
        profile: 'الملف الشخصي',
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: typeof translations['en'];
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'en';
    });

    const isRTL = language === 'ar';

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language, isRTL]);

    const value = {
        language,
        setLanguage,
        t: translations[language],
        isRTL,
    };

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
